export { default as entity } from './core/entity'
export { default as useEntity } from './core/useEntity'
export { strictEqual, shallowEqual } from './core/equality'
export { default as alias } from './plugins/alias'
export { default as persistence } from './plugins/persistence'
export { enableInspector } from './tools/inspector'
export { enableStore } from './tools/store'
export { default as resetAll } from './tools/resetAll'
